services:
  - type: web
    name: cerberu-agente-ia
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: OPENAI_API_KEY
        fromDatabase: false
      - key: DATABASE_URL
        fromDatabase: false
